### ISSUE TITLE
Feature: automatically renew the geometry objects when the axis scale changes

### ISSUE THREAD

**Issue by TienanLi** [genyez/MaterialPlot#20]
dependent on Issue #18 
need to refactor the transformer a bit to handle geometry_obj -> geometry_obj conversion.

**Comment by genyez** [comment]
the viewScale field in AGraphicsView should be what you need.
resetSceneRect of AGraphicsView will be called whenever the viewScale changes, so you can make a signal emitted from resetSceneRect and handle it, if you need.

**Comment by TienanLi** [comment]
resolved in [4ba99ca](https://github.com/genyez/MaterialPlot/commit/4ba99caf98d3602d7487ac1b293fb9f9e2a2dcd3)
Handle the feature by adding a cache of semantic items for convenient redraw. The reason is that graphic items already lose the original information needed for conversion. For example, it's much easier and more robust to do "[items, in_linear] -> linear_hull" and "[items, in_log] -> log_hull" independently instead of linear_hull->log_hull (not even sure if it's possible).

A long-term ticket for me is to consolidate the semantic_items and graphic_items caches. Right now these two are independent and users need to guarantee consistency. - might consider wrapping them under a simple struct like item_info including both the graphic and semantic things.

**Comment by TienanLi** [comment]
btw can't do it in resetSceneRect because it is too frequently called (e.g. when in mouse_movement), we don't need to update objects so frequently, as it is only needed in update_config, so put the feature there.
