### ISSUE TITLE
a vis bug at drawHull()

### ISSUE THREAD

**Issue by TienanLi** [genyez/MaterialPlot#22]
For unknown reasons, there seems to be an additional layer when we implement drawHull in the log scale.

![84cf64c55efbb4f6fc3447e89bcc557](https://user-images.githubusercontent.com/47532644/193438390-dcaed83f-80b1-4511-b261-ddd775db1c28.png)

The hull_v var in the drawHull() function should be a well-defined polygon.
![d20714198d92998dd2a8b0efbe1c48f](https://user-images.githubusercontent.com/47532644/193438412-3418fce5-bf80-4887-892f-b108766e0c4a.jpg)
debug log point set:
[[ 2.06977205, -2.21475878],
 [ 0.63541327, -1.78261018],
 [ 0.63389995, -1.78215876],
 [ 0.63236477, -1.78173767],
 [ 0.63080927, -1.78134734],
 [ 0.629235  , -1.78098816],
 [ 0.62764352, -1.78066048],
 [ 0.62603642, -1.78036463],
 [ 0.6244153 , -1.7801009 ],
 [ 0.62278178, -1.77986956],
 [ 0.62113749, -1.77967084],
 [ 0.61948407, -1.77950494],
 [ 0.61782316, -1.77937202],
 [ 0.61615643, -1.77927221],
 [ 0.61448552, -1.77920562],
 [ 0.61281211, -1.7791723 ],
 [ 0.61113787, -1.7791723 ],
 [ 0.60946446, -1.77920562],
 [ 0.60779356, -1.77927221],
 [ 0.60612682, -1.77937202],
 [ 0.60446591, -1.77950494],
 [ 0.60281249, -1.77967084],
 [ 0.29056303, -1.81668643],
 [ 0.28852802, -1.81697428],
 [ 0.28650426, -1.81731907],
 [ 0.28449375, -1.81772046],
 [ 0.2824985 , -1.81817804],
 [ 0.28052051, -1.81869135],
 [ 0.27856174, -1.81925989],
 [ 0.27662414, -1.8198831 ],
 [ 0.27470966, -1.82056034],
 [ 0.27282018, -1.82129094],
 [ 0.27095761, -1.82207418],
 [ 0.26912379, -1.82290928],
 [ 0.26732056, -1.8237954 ],
 [ 0.26554971, -1.82473165],
 [ 0.263813  , -1.82571711],
 [ 0.26211218, -1.8267508 ],
 [ 0.26044892, -1.82783167],
 [ 0.2588249 , -1.82895866],
 [ 0.25724172, -1.83013065],
 [ 0.25570098, -1.83134646],
 [ 0.2542042 , -1.83260488],
 [ 0.25275287, -1.83390465],
 [ 0.25134845, -1.83524449],
 [ 0.24999233, -1.83662306],
 [ 0.24868586, -1.83803897],
 [ 0.24743036, -1.83949083],
 [ 0.24622706, -1.84097718],
 [ 0.24507716, -1.84249654],
 [ 0.24398182, -1.8440474 ],
 [ 0.24294213, -1.84562821],
 [ 0.24195912, -1.84723739],
 [ 0.24103377, -1.84887335],
 [ 0.24016701, -1.85053445],
 [ 0.23935969, -1.85221903],
 [ 0.23861263, -1.85392541],
 [ 0.23792656, -1.85565191],
 [ 0.23730218, -1.85739678],
 [ 0.2367401 , -1.8591583 ],
 [ 0.23624089, -1.86093471],
 [ 0.23580504, -1.86272423],
 [ 0.23543298, -1.86452509],
 [ 0.2351251 , -1.86633549],
 [ 0.23488168, -1.86815362],
 [ 0.23470299, -1.86997767],
 [ 0.23458919, -1.87180583],
 [ 0.2345404 , -1.87363626],
 [ 0.23455666, -1.87546715],
 [ 0.23463797, -1.87729668],
 [ 0.23478423, -1.87912301],
 [ 0.23499531, -1.88094433],
 [ 0.235271  , -1.88275882],
 [ 0.23561101, -1.88456467],
 [ 0.23601502, -1.88636009],
 [ 0.23648261, -1.88814327],
 [ 0.23701332, -1.88991246],
 [ 0.23760662, -1.89166587],
 [ 0.23826193, -1.89340177],
 [ 0.23897858, -1.89511843],
 [ 0.23975587, -1.89681412],
 [ 0.24059301, -1.89848717],
 [ 0.24148918, -1.9001359 ],
 [ 0.24244348, -1.90175867],
 [ 0.24345495, -1.90335387],
 [ 0.2445226 , -1.9049199 ],
 [ 0.24564536, -1.9064552 ],
 [ 0.2468221 , -1.90795824],
 [ 0.24805166, -1.90942753],
 [ 0.24933281, -1.9108616 ],
 [ 0.25066427, -1.91225901],
 [ 0.25204471, -1.91361838],
 [ 0.25347276, -1.91493835],
 [ 0.254947  , -1.91621761],
 [ 1.86345578, -3.25392281],
 [ 1.86436866, -3.25457936],
 [ 2.52148042, -3.67285207],
 [ 2.52340668, -3.67407379],
 [ 2.52540859, -3.67526428],
 [ 2.52748416, -3.67642237],
 [ 2.5296313 , -3.67754689],
 [ 2.53184789, -3.67863672],
 [ 2.53413171, -3.67969078],
 [ 2.53648048, -3.68070802],
 [ 2.53889187, -3.68168742],
 [ 2.54136346, -3.68262801],
 [ 2.54389281, -3.68352884],
 [ 2.54647738, -3.68438903],
 [ 2.5491146 , -3.68520771],
 [ 2.55180184, -3.68598407],
 [ 2.55453642, -3.68671734],
 [ 2.55731561, -3.68740677],
 [ 2.56013665, -3.6880517 ],
 [ 2.56299673, -3.68865146],
 [ 2.56589298, -3.68920547],
 [ 2.56882253, -3.68971317],
 [ 2.57178246, -3.69017406],
 [ 2.57476981, -3.69058768],
 [ 2.57778161, -3.69095361],
 [ 2.58081485, -3.69127149],
 [ 2.58386651, -3.69154101],
 [ 2.58693355, -3.69176189],
 [ 2.59001291, -3.69193391],
 [ 2.59310152, -3.69205691],
 [ 2.59619631, -3.69213076],
 [ 2.59929418, -3.69215538],
 [ 2.60239206, -3.69213076],
 [ 2.60548684, -3.69205691],
 [ 2.60857546, -3.69193391],
 [ 2.61165482, -3.69176189],
 [ 2.61472186, -3.69154101],
 [ 2.61777352, -3.69127149],
 [ 2.62080676, -3.69095361],
 [ 2.62381856, -3.69058768],
 [ 2.62680591, -3.69017406],
 [ 2.62976583, -3.68971317],
 [ 2.63269538, -3.68920547],
 [ 2.63559164, -3.68865146],
 [ 2.63845171, -3.6880517 ],
 [ 2.64127275, -3.68740677],
 [ 2.64405195, -3.68671734],
 [ 2.64678653, -3.68598407],
 [ 2.64947377, -3.68520771],
 [ 2.65211099, -3.68438903],
 [ 2.65469556, -3.68352884],
 [ 2.6572249 , -3.68262801],
 [ 2.6596965 , -3.68168742],
 [ 2.66210789, -3.68070802],
 [ 2.66445666, -3.67969078],
 [ 2.66674048, -3.67863672],
 [ 2.66895706, -3.67754689],
 [ 2.67110421, -3.67642237],
 [ 2.67317977, -3.67526428],
 [ 2.67518168, -3.67407379],
 [ 2.67710795, -3.67285207],
 [ 2.67895665, -3.67160035],
 [ 2.68072594, -3.67031987],
 [ 2.68241405, -3.6690119 ],
 [ 2.68401932, -3.66767776],
 [ 2.68554012, -3.66631877],
 [ 2.68697496, -3.66493629],
 [ 2.68832239, -3.66353169],
 [ 2.68958107, -3.66210638],
 [ 2.69074976, -3.66066177],
 [ 2.69182728, -3.65919931],
 [ 2.69281256, -3.65772045],
 [ 2.69370462, -3.65622667],
 [ 2.69450258, -3.65471946],
 [ 2.69520562, -3.65320031],
 [ 2.69581306, -3.65167075],
 [ 2.69632429, -3.6501323 ],
 [ 2.69673879, -3.64858649],
 [ 2.69705616, -3.64703486],
 [ 2.69727608, -3.64547896],
 [ 2.69739833, -3.64392034],
 [ 2.69742278, -3.64236055],
 [ 2.69734942, -3.64080116],
 [ 2.69717832, -3.6392437 ],
 [ 2.69690964, -3.63768975],
 [ 2.69654366, -3.63614083],
 [ 2.69608073, -3.63459851],
 [ 2.69552133, -3.63306431],
 [ 2.11363838, -2.26704152],
 [ 2.11195459, -2.26309478],
 [ 2.11021807, -2.25927362],
 [ 2.10843054, -2.25558185],
 [ 2.10659378, -2.25202314],
 [ 2.10470963, -2.24860106],
 [ 2.10277997, -2.245319  ],
 [ 2.10080672, -2.24218024],
 [ 2.09879184, -2.23918791],
 [ 2.09673734, -2.23634499],
 [ 2.09464528, -2.23365431],
 [ 2.09251773, -2.23111857],
 [ 2.09035683, -2.22874028],
 [ 2.08816471, -2.22652181],
 [ 2.08594358, -2.22446538],
 [ 2.08369563, -2.22257304],
 [ 2.08142312, -2.22084667],
 [ 2.0791283 , -2.219288  ],
 [ 2.07681347, -2.21789857],
 [ 2.07448093, -2.21667978],]

**Comment by genyez** [comment]
fixed in 81e92551,QPen width set to zero
